### ISSUE TITLE
Cant run go get -u github.com/segmentio/chamber

### ISSUE THREAD

**Issue by rv-acoulter** [segmentio/chamber#163]
Hey all we run go get at deployment using aws amazon fargate and is returning a non zero error code preventing us from deploying.

This error has happened before and was report in issue #137 

```
[AWS CodeBuild Plugin] {"errorDetail":{"code":2,"message":"The command '/bin/sh -c go get -u github.com/segmentio/chamber' returned a non-zero code: 2,"error":"The command '/bin/sh -c go get -u github.com/segmentio/chamber' returned a non-zero code: 2```

**Comment by nickatsegment** [comment]
Damn, that was fast. Yeah, the build was broken by a bad merge.

I would *highly* recommend downloading the binary directly instead. And you should really bake it into the image. We're never going to be able to guarantee is never broken.

I'm considering deprecating the `go get` installation method because it's so fragile.

**Comment by nickatsegment** [comment]
@rv-acoulter 	I'm pretty sure this is fixed.

**Comment by nickatsegment** [comment]
@rv-acoulter 	I would love your input at https://github.com/segmentio/chamber/issues/164

**Comment by rv-acoulter** [comment]
@nickatsegment we are planning to change the way we are installing and use the method you mentioned. We just haven't gotten around to making the change in all of the services. Thank you for the fast fix!
