### ISSUE TITLE
Operational Question- What's best practice for reloading services when parameters change?

### ISSUE THREAD

**Issue by jeffnappi** [segmentio/chamber#178]
As the title states - What is a good procedure/practice for reloading dependent services when parameters change?

Would it be sensible to have chamber itself restart a service when parameters change? (perhaps via a flag of some sort, and have it poll for config changes periodically)

**Comment by nickatsegment** [comment]
It really depends on your app. In the simplest case, say it's a stateless microservice with an API token to a 3rd party service running in ECS. I'd have it exit when it finds out the token doesn't work, then ECS would restart it.

`chamber exec` execs the child process, and doesn't fork or anything that would allow it to do any restarting of the child. Making it a process supervisor would be a pretty decent chunk of work.

Another scenario: say you're running Prometheus with a Slack API token templated into the config file by some chamber start up script. Since Prometheus supports hot reloading of the config (including the token), you could do it with zero downtime. I would argue that that logic belongs in the start up script though, since you'd need to coordinate the SIGHUP.
