### ISSUE TITLE
use '/' for hierarchy rather than '.'

### ISSUE THREAD

**Issue by echo0101** [segmentio/chamber#22]
Would it make sense to use '/' to create a hierarchy rather than using the '.'? This way we could use IAM permissions to create service-level access policies to the parameters.

For example,
```
chamber write myservice foo 1234
```
would yield a parameter named: `myservice/foo` and we could use the following statement for the service:
```
 {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParametersByPath"
            ],
            "Resource": "arn:aws:ssm:us-east-1:123456789:parameter/myservice/*"
}
```

Doc: http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-working.html

**Comment by dfuentes** [comment]
You can use the same scheme with "." separators as well, with the policy:

```json
 {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameters"
            ],
            "Resource": "arn:aws:ssm:us-east-1:123456789:parameter/myservice.*"
}
```

We are planning to switch to "/" for path separation soon though (https://github.com/segmentio/chamber/pull/23).  It's a little delicate because we have a large number of parameters and consumers internally that need to be migrated, but we hope to have it done within the week.

Along with this update, we will add documentation around how to set up IAM policies to play nicely with our key scheme.

**Comment by echo0101** [comment]
Thanks for the quick response! I did not realize that the the same thing could be achieved with the dot notation. I'll close this request out then. Look forward to your changes in #23!
