### ISSUE TITLE
Support writing secret from a file

### ISSUE THREAD

**Issue by max-lobur** [segmentio/chamber#226]
Use case:
`chamber write my_service git_ssh_key ~/.ssh/key`
SSH keys are sensitive to trailing `\n` so it would be much easier to import that directly from a file.

**Comment by max-lobur** [comment]
Well, there's more than that. Sounds like SSM when you're getting parameter in json removes the trailing newline too. So had to hack it by adding another one :(
https://github.com/max-lobur/dotfiles/blob/master/sh/chamber_write_file.sh

**Comment by nickatsegment** [comment]
That's the first I've heard of it dropping newlines. That sucks :(

You could use `chamber import` to get better control. If I recall correctly, it won't touch any other keys for the service besides the ones in the JSON.

**Comment by max-lobur** [comment]
Yeah I've used `export->edit->import->export` and `write try ssm -> export` to verify - both cut me newline. I think it might be json encoder in api. Anyways, I have a workaround now. Once I can write files directly via chamber I can test further, and maybe include the newline hack to chamber too

**Comment by max-lobur** [comment]
still actual

**Comment by vincent-czi** [comment]
For context, I'm running `chamber v2.13.0` and it's close to five years after the original post, so who knows if any of the below used to work.

I found this issue because I had basically the exact same use case as OP. I wanted to do something like
```chamber write my_service git_ssh_key ~/.ssh/key```
and then be able to write the env var into a file that would be identical to the original when a service starts up. I was worried about the handling of newlines and wasn't really confident I knew what chamber's behavior would be from the README.

I wound up experimenting for a bit and found a pretty simple solution. Posting it here in case it winds up being useful to anyone else looking for a way to leverage chamber for writing (small-ish) secret files.

To load the file contents in to chamber, run the below
```
cat my_file | chamber write my_service my_file_key -
```

Then to replicate the original file in some service, you can run
```
chamber exec my_service -- ./entrypoint.sh
```
Where `entrypoint.sh` will contain a line like this to replicate the file before whatever code in entrypoint makes use of that file
```
echo -n "$MY_FILE_KEY" > my_file
```
In my experiments, that appears to write the entirety of the file, newlines fully respected. I saw both newlines in the file and trailing newline or lack thereof respected; it was a perfect copy of the original `my_file`, whatever the contents I used.
