### ISSUE TITLE
App versioning

### ISSUE THREAD

**Issue by rt-alex** [segmentio/chamber#240]
Is there any solution for deploying different App versions which may have different secret values?

Use case: Canary or A/B
AppV1 and AppV2 are identical except for one secret value has changed.
Node A should run AppV1
Node B should run AppV2

**Comment by nickatsegment** [comment]
Besides just copying to a new service with a suffix or something? No, not really.

One thing you could do is chain chamber: `chamber exec app-v1 -- chamber exec app-v2 -- runmyprogram`

You'd have to make sure that `app-v2` only contains that one value, otherwise it could override the ones in `app-v1`.
