### ISSUE TITLE
Enhance chamber export or write to accept tier parameter for AWS SSM

### ISSUE THREAD

**Issue by brickstar** [segmentio/chamber#282]
Hi,

Thanks for providing this excellent open source software, our team has been using it with great success! :heart: ❤️

Recently we wanted use chamber to manage a pgp decryption key secret that exceeded the character limit enforced by the `Standard` tier of AWS SSM. We ended up creating two secrets, but I was wondering if it was reasonable to request an enhancement for export or write to accept a `<tier>` parameter in order to push `Advanced` tier secrets.

Thanks! 
Matt

**Comment by nickatsegment** [comment]
Yeah, seems reasonable. I don't think Segment would use it TBH, so you'd have to find someone to write it.

Feel free to sketch out what the CLI flags would look like here.

**Comment by brickstar** [comment]
Sounds great, thanks for the reply.

**Comment by joeybaer** [comment]
@brickstar What about changing your parameter store default tier to [intelligent tiering](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-advanced-parameters.html#ps-default-tier) which you can do in the parameter store settings. I believe that would would abstract any logic from chamber/user end when handling secrets since AWS will decide the appropriate tier automatically.
