### ISSUE TITLE
Feature: Runtime include support for shared secret groups

### ISSUE THREAD

**Issue by jdwilly2001** [segmentio/chamber#288]
I have a use case in which we have secrets which are managed by different groups of people. Also some keys and secrets are shared between several different microservices. Updating/modifying the secrets individually in chamber can take some time.

I would like to introduce a feature into chamber to allow run-time includes of other services. This would allow the team to create a shared secret group for a particular product, and then allow microservices within that product or application to reference the same secret in the underlying store.

Current use case is using the SSM store, but it would be store-dependent on the support of this feature. Also the implementation details would be left to the underlying store. 

Proposed SSM implementation is to use a service metadata key "__chamber.service.metadata" in the service which is a JSON document which contains additional instructions when processing requests for a particular service. If the metadata is not present, the operation continues without issue. If the metadata is present, then it can influence the processing for List, ListRaw, Read or other operations.

Thoughts or ideas on if this is a fit for chamber?

**Comment by nickatsegment** [comment]
I think this makes sense. To summarize and check my understanding, we would add some metadata that would reference secrets outside the current service, and chamber would resolve those references and present them as if they were from the current service.

I like the idea, so yeah, please go ahead. I think there are some implementation details we should hammer out here first. I'll start in a separate comment.

**Comment by nickatsegment** [comment]
Do we want cross-backend references? I think this would be cool; it'd allow for migrations to a new backend while keeping the old backend working. In a way, it would allow us to abstract away the whole `--backend` flags, and just store that info in SSM, considering it the source of truth. I'd say this is nice to have, not a requirement for this feature.

The choice of name for the metadata key. I'd prefer `/<service>/__chamber_metadata` or something, rather than adding a top-level `__chamber` namespace. Also, I feel like the the term `metadata` is overused; I'd prefer something concrete like `__chamber_links` or something. Not a strong feeling though.

Instead of a JSON document, maybe we could just have a magic key prefix, with the value being some sort of reference URL. The prefix gets trimmed, then the trimmed key is returned with the resolved value.

Perhaps we could store the links in non-encrypted values or some other SSM metadata somehow? Imagine your service *only* has links; I'd argue it doesn't need IAM perms to read the values under there then, only the values in the referenced "service". Do links *need* to be encrypted? I'd guess no.

Do you think we should have this feature flagged and off by default? Then on by default in v3? You'd have to opt-in by writing the `metadata` key in the first place, so maybe that's implied. However, requiring opt-in with a flag could make it clearer if you're on an older version without this feature and you're not seeing references being resolved: instead it would fail because the flag would be invalid.

What's the interface for writing this `metadata` key look like for the CLI? If we were to use individual keys with a magic prefix to represent an individual link, we could probably just use `write` with a flag. Otherwise, it might be a new command?

**Comment by nickatsegment** [comment]
> some other SSM metadata
Had a look and I'm not seeing much jump out. [There's the `Description` field.](
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribeParameters.html)

At any rate, requiring the caller to have the ability to read and decrypt values doesn't seem like a huge ask, so maybe this is not worth persuing.

**Comment by jdwilly2001** [comment]
> Do we want cross-backend references? 
I think this would be a great feature to support migrations. There would be some store connectivity params required to be added to the 'link' metadata but seems possible.

> The choice of name for the metadata key. I'd prefer /<service>/__chamber_metadata or something, rather than adding a top-level __chamber namespace. Also, I feel like the the term metadata is overused; I'd prefer something concrete like __chamber_links or something. Not a strong feeling though.

Agreed. This is a service level metadata and should not live in a 'top level' key. I was suggesting these meta keys be located within the service. 

JSON vs Magic?
I also thought about storing in encoded format due to size restrictions on some backends. This was weighed against troubleshooting and debug ability to examine the records outside of chamber using AWS console. Implementation should be store dependent, and what makes most sense for the store. 

Encryption
I do not feel metadata in general should be encrypted. However, in some cases the metadata may contain info on cross-reference stores. This may lead to authentication data required to access another backend store. This would need to be encrypted.

Feature Enablement
Was thinking these features were passively supported by the stores after a certain version. The meta keys to add additional processing features could be supported by different stores in different versions? Since the implementation is store dependent. The store would quietly move on if the meta keys were not present. Flags to modify failure conditions make sense like '--require link' to fail if linked services are not found? If the store does not support a feature, it would return a NotYetImplemented error message.

Interface
For the 'service link' feature, i was considering adding a CLI link command to register a reference within another service. Something like 
`chamber link <service> <shared-service>` 
**service** would be the main application service and the **shared-service** would be the service that contained additional shared secrets. Additional flags and parameters could be added to this command to support the cross-backend loading. Without providing any flags, the **shared-service** is assumed to be in the same backend as the main service and would be processed as such by the underlying store.
