### ISSUE TITLE
Google Cloud Authentication

### ISSUE THREAD

**Issue by soltex1** [segmentio/chamber#299]
I am trying to use the [google service account](https://cloud.google.com/docs/authentication/getting-started) especially the **GOOGLE_APPLICATION_CREDENTIALS** env var.

The problem is that **GOOGLE_APPLICATION_CREDENTIALS** is a file path of the JSON file that contains the service account key.

eg: `GOOGLE_APPLICATION_CREDENTIALS=$home/service_key.json`

I am trying to run this:

`./cloud_sql_proxy -credential_file=PATH_TO_JSON`

It would be great if I could do this:

`./cloud_sql_proxy -credential_file=$(chamber exec get_path GOOGLE_SECRETS)`

Is there a way to solve this using chamber?

**Comment by nickatsegment** [comment]
There's no way for chamber to write to a file natively. This is by design: when would that file get cleaned up?

You can accomplish this with shell hacks though: `./cloud_sql_proxy -credential_file=<(chamber exec get_path GOOGLE_SECRETS)`. Bash calls this <a href="https://superuser.com/questions/1059781/what-exactly-is-in-bash-and-in-zsh">"process substition"</a>. (Not all programs will support this well, though, so you might need to do some tempfile hack yourself.)

**Comment by soltex1** [comment]
@nickatsegment it did work! thank you so much for your help!

Here's how:

```
./cloud_sql_proxy
  -instances=INSTANCE_NAME=tcp:3306 
  -credential_file=<(aws-vault exec ENVIRONMENT -- chamber read SERVICE KEY  -q)
```
