### ISSUE TITLE
Different env var to select region?

### ISSUE THREAD

**Issue by opb** [segmentio/chamber#51]
Hi.

Love the project, and I had an idea which I wanted to float.

We're in a position where we deploy a service across multiple regions, and it requires the same secrets to be saved, regardless of region. We have two options at the moment:

1. Manage a key for each region, ensuring data is synchronised between them
2. Manually force the `AWS_REGION` env var so that they all use the same region to look for the key.

The issue with the second option is that other parts of the system could be making use of `AWS_REGION` and might actually need that to work as intended.

Another option could be to look for a different var (e.g. `CHAMBER_KMS_REGION`) just before https://github.com/segmentio/chamber/blob/master/store/ssmstore.go#L42 and use that instead. I'd be interested to hear your thoughts on this idea!

Thanks

**Comment by abraithwaite** [comment]
Sounds like you need to ensure the IAM role has access to all regions.

I believe you can use a `*` for the region in the ARN for the permission where the region is. [1][2]

You can then either let chamber infer it's own region using the Metadata API or keep `AWS_REGION` set to the current region instead of the region you created the parameter in.

@ejcx and @dfuentes, please correct me if I'm wrong.

[1] https://aws.amazon.com/blogs/mt/the-right-way-to-store-secrets-using-parameter-store/
[2] http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html

**Comment by ejcx** [comment]
Yuck! I don't think we considered this too much.

I think the easy fix is to have an extra ENV var like you pointed out, or some other mechanism so you don't clobber your `AWS_REGION` variable.

I can also think of a kind of hacky way to do this where you export the secrets to an encrypted file (with a key that is generated on the fly). Then it doesn't have to be run all at once and it can still be secure.

@dfuentes is honestly the sane one here though =]. Ill chat with him about it.

**Comment by opb** [comment]
Hey, thanks for the responses. I had a think about some kind of wrapper around chamber exec, but thought I'd bring up the env var suggestion, as it's a fair bit less work ;)

Thanks

**Comment by dfuentes** [comment]
Totally seems reasonable to add an override environment variable.  I will draft up a PR for this

**Comment by opb** [comment]
Thanks so much for this!
