### ISSUE TITLE
Intended workflow for docker restart policy always

### ISSUE THREAD

**Issue by ironhouzi** [segmentio/chamber#72]
From what I understand, `chamber` is either added to the docker image (or used as a sidecar?) with the AWS tokens set as environment variables and the chamber executable is prepended to the entrypoint. As I understand this will rerun chamber every time the container fails, and if I understand AWS correctly, the AWS tokens will expire after some time and then the container needs new tokens, requiring manual intervention.

Is there a better way to automate this situation?

**Comment by dfuentes** [comment]
You have several options depending on your deployment scenario.  I would avoid explicitly passing in credentials if possible, and instead rely on credentials provided by the EC2 metadata service (which will automatically generate new security tokens as necessary).  How you do this will depend on how you are deploying your application:

For plain EC2 instances, there are [EC2 Instance Roles](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).

If you are on ECS, there is a similar concept with [Task Roles](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html).  When you attach an IAM role to your ECS task, it works similarly to EC2 instance roles in that chamber will pull credentials from the EC2 metadata service.

For local development, you can use aws-vault's `--server` flag to emulate the EC2 metadata service.

**Comment by ironhouzi** [comment]
Sorry, forgot to add the vital information of not running in my container in an AWS context .. Is chamber not intended to run outside of an AWS context, EC2 or ECS.. or whatever other offering AWS might have?

**Comment by dfuentes** [comment]
It's possible, but we don't currently do this (other than for local development).  Without knowing more about your setup, I'm not sure how much help I'm going to be.

In general, you could use the key/secret of an IAM User rather than an IAM role, which would allow you to use static credentials that don't need to refresh.  The downside there is that if those credentials are leaked, they are useable as is.

Roles are more secure in that they require a short term security token, but you would need some process to acquire the role access key id, secret, and security token and inject that into your docker container somehow.

**Comment by ironhouzi** [comment]
@dfuentes I was hoping chamber/APS would be a simple alternative to Hashicorp's Vault, securely providing secrets for microservices in automated deployments, managed through IAM concepts.

If fixed IAM user is the only option outside of deploying on AWS, then I'd need to keep looking for alternatives.
