### ISSUE TITLE
Support for empty values

### ISSUE THREAD

**Issue by mkj28** [segmentio/chamber#91]
Might not make a lot of sense, but bear there with me - the use case is for chamber reading keys from the parameter store - and be able to have environment variables with empty values ("").

Parameter Store has [this feature request](https://forums.aws.amazon.com/message.jspa?messageID=419466) 6 years in the making, so not likely to support. (its for CloudFormation, but root cause seems to be the same).

Feature request to chamber is to work around it by, probably, using some sort of placeholder for empty values.

**Comment by otterley** [comment]
Out of curiosity, what's your use case?  

My first thought is that since there's no common textual identifier representing an empty value that cannot be mistaken for the text itself, that what you're asking for isn't really possible in the general case. 

So, I'd recommend that you designate your own internal alias for an empty value, and that the software reading the value via Chamber should perform the aliasing itself.

**Comment by mkj28** [comment]
> Out of curiosity, what's your use case?

For example we had SENTRY_DSN blank in an environment we did not need sentry.io reporting. For convenience/consistency we had the key defined across all environments with blank value where not needed.

We discussed having internal alias for empty value, but eventually settled on not defining the key at all instead.

**Comment by nickatsegment** [comment]
I can imagine it being useful, but pretty edge case. If you can find more users, I'd consider including it. For one-offs though, you could just do special case a sentinel value I'd say
